tabWidth: 4
printWidth: 190
singleQuote: true
trailingComma: all
endOfLine: lf
quoteProps: as-needed
jsxSingleQuote: false
bracketSpacing: true
bracketSameLine: false
arrowParens: always
importOrderSeparation: false
importOrderSortSpecifiers: true
importOrder:
    - 'reflect-metadata'
    - 'source-map-support/register'
    - '../../config/'
    - './lib/config'
    - 'react'
    - '<THIRD_PARTY_MODULES>'
    - '^[./]'
importOrderParserPlugins:
    - 'typescript'
    - 'jsx'
    - 'decorators-legacy'
